# Generated by Django 2.1.1 on 2018-09-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('isbn', models.BigIntegerField(default=0, null=True)),
                ('isbn_13', models.BigIntegerField(default=0, null=True)),
                ('publication_date', models.IntegerField(default=-1, null=True)),
                ('ratings_count', models.BigIntegerField(default=0, null=True)),
                ('average_ratings', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('cover_image_url', models.URLField(null=True)),
                ('authors', models.ManyToManyField(blank=True, to='author.Author')),
            ],
        ),
    ]
